---
# tasks file for prometheus-grafana-compose
    - name: Create dir for prometheus yml conf file
      file:
         path: /etc/prometheus
         owner: "{{ user }}"
         group: "{{ group }}"
         mode: 0700
         state: directory

    - name: Generate yml conf for prometheus
      template:
          src: 'prometheus.yml.j2'
          dest: '/etc/prometheus'
          owner: "{{ user }}"
          group: "{{ group }}"
          mode: 0700

    - name: Copy docker compose file
      copy:
         src: 'monitoring-compose.yml'
         dest: '/home/prometheus'
         owner: "{{ user }}"
         group: "{{ group }}"
         mode: 0700
         
    - name: Run docker compose
      docker_compose:
            project_src: '/home/{{ user }}'
            files:
                - monitoring-compose.yml
      register: output
       
    - name: Show results
      debug:
        var: output
