---
# tasks file for prometheus-grafana-compose
    - name: Copy docker compose file
      copy:
         src: 'monitoring-compose.yml'
         dest: '/home/{{ user }}'
         owner: "{{ user }}"
         group: "{{ group }}"
         mode: 0700
         
    - name: Run docker compose
      docker_compose:
            project_src: '/home/{{ user }}'
            files:
                - monitoring-compose.yml
      register: output
       
    - name: Show results
      debug:
        var: output
