---
# handlers file for node-exporter
    - name: restart_node_exporter
      systemd:
         name: "{{ service_name }}" 
         state: restarted
         daemon_reload: yes
         enabled: yes
